/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demoDrawArcs;

import java.awt.*;

/**
 *
 * @author barkera2020
 */
public class DrawArcPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawObjectPanel
     */
    
    private TheArc arc1, arc2, arc3, arc4, arc5;

    public DrawArcPanel() {
        initComponents();
        
        arc1 = new TheArc(20, 20, 50, 50, 180, 180);
        arc2 = new TheArc(140, 20, 50, 50, 360, 180);
        arc3 = new TheArc(20, 140, 50, 50, 360, 270);
        arc4 = new TheArc(140, 140, 50, 50, 180, 270);
        arc5 = new TheArc(260, 20, 50, 50, 360, 360);
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        g.setColor(Color.RED);
        g.fillRect(0, 0, 1000, 1000);
        
        arc1.draw(g);
        arc2.draw(g);
        arc3.draw(g);
        arc4.draw(g);
        arc5.draw(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
