/*
 * Jim Klayder -- fall 2018
 * 
 * demo of a few recursive calculation routines

https://en.wikipedia.org/wiki/Recursion

A method is recursive if it calls itself.

A basic recursive routine can be set up using an if-else statement.
Example:

private int summation(int num) {
    if (num <= 1)
    {
        return num;
    }else
    {
        return num + summation(num - 1);
    }
}

NOTE: 1. The if clause is the basis with no recursive call.
      2. The else clause includes a recursive call with a parameter
            value that GETS CLOSER TO THE BASIS.

 */
package demoRecursionExample;

import java.awt.Point;

/**
 *
 * @author jimklayder
 */
public class PrintingFrame extends javax.swing.JFrame {

    private DrawingPanel drawingPanel;
    
    /**
     * Creates new form MainFrame
     */
    public PrintingFrame() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTwo = new javax.swing.JButton();
        buttonThree = new javax.swing.JButton();
        buttonOne = new javax.swing.JButton();
        buttonFive = new javax.swing.JButton();
        buttonFour = new javax.swing.JButton();
        buttonSix = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        fieldThreeInput = new javax.swing.JTextField();
        fieldFourInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonTwo.setText("two");
        buttonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTwoActionPerformed(evt);
            }
        });

        buttonThree.setText("three");
        buttonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThreeActionPerformed(evt);
            }
        });

        buttonOne.setText("one");
        buttonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneActionPerformed(evt);
            }
        });

        buttonFive.setText("five");
        buttonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiveActionPerformed(evt);
            }
        });

        buttonFour.setText("four");
        buttonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFourActionPerformed(evt);
            }
        });

        buttonSix.setText("six");
        buttonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSixActionPerformed(evt);
            }
        });

        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        fieldThreeInput.setText("5");

        fieldFourInput.setText("4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldFourInput, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(fieldThreeInput))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonThree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(buttonFour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttonOne)
                .addGap(18, 18, 18)
                .addComponent(buttonTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonThree)
                    .addComponent(fieldThreeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFour)
                    .addComponent(fieldFourInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(buttonFive)
                .addGap(18, 18, 18)
                .addComponent(buttonSix)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOneActionPerformed
        System.out.println("button one");
        outputArea.setText("\n");
        countDown(9);
    }//GEN-LAST:event_buttonOneActionPerformed

    private void countDown(int num) {
        if (num <= 1)
        {
            outputArea.append("    "+num+"\n");
        }else
        {
            outputArea.append("  "+num);
            countDown(num - 1);
        }
    }
    
    private void buttonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTwoActionPerformed
        System.out.println("button two");
        outputArea.setText("");
        count2(9);
    }//GEN-LAST:event_buttonTwoActionPerformed

    private void count2(int num) {
        if (num <= 1)
        {
            outputArea.append("    "+num+"\n");
        }else
        {
            for (int i = 0; i < num; i++) 
            {
                outputArea.append("     ");
            }
            outputArea.append("  "+num+"\n");
            
            count2(num - 1);
        }
    }
    
    private void buttonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThreeActionPerformed
        System.out.println("button three");
        int theNum = 0;
        outputArea.setText("");
        try
        {
            theNum = Integer.parseInt(fieldThreeInput.getText());
        }catch (Exception ex){
            outputArea.append("\n  Sorry, '"+fieldThreeInput.getText()+"' could not be parsed as an integer.");
            outputArea.append("\n\n  Please enter an integer greater than 0 and less than 10000");
            
            outputArea.append("\n\n  For now we will use 5.");
            theNum = 5;
        }
        
        if (theNum <= 0 || theNum >= 10000)
        {
            outputArea.append("\n\n  Please enter an integer greater than 0 and less than 10000");
            
            outputArea.append("\n\n  For now we will use 5.");
            theNum = 5;
        }
        outputArea.append("\n\n\n   int total = summation("+theNum+");   \n\n");
        
        int total = summation(theNum);
        outputArea.append("          total is  "+total);
        
    }//GEN-LAST:event_buttonThreeActionPerformed

    
    private int summation(int num) {
        if (num <= 1)
        {
            return num;
        }else
        {
            return num + summation(num - 1);
        }
    }
    
    private void buttonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFourActionPerformed
        System.out.println("button four");
        
        
        outputArea.setText("\n    Fibonacci sequence   \n\n");
        int theNum = 0;
        try
        {
            theNum= Integer.parseInt(fieldFourInput.getText());
        }catch (Exception ex){
            outputArea.setText("\n  Sorry, '"+fieldThreeInput.getText()+"' could not be parse as an integer.");
            outputArea.append("\n\n  Please enter an integer greater than 0 and less than 10000");
            
            outputArea.append("\n\n  For now we will use 5.");
            theNum = 5;
        }
        
        if (theNum <= 0)
        {
            outputArea.setText("\n\n  Please use a positive integer.");
            outputArea.append("\n\n  '"+theNum+"' is too small.");
            outputArea.append("\n\n  For now we will use 5.");
            theNum = 5;
        }
        if (theNum > 40)
        {
            outputArea.append("\n   (Sorry, "+theNum+" is too big.)   \n\n");
            outputArea.append("\n   (40 is the largest number allowed.)   \n\n");
        }else
        {
            outputArea.append("\n   ("+theNum+" numbers)   \n\n");
            showFibo(theNum);
        }
        
    }//GEN-LAST:event_buttonFourActionPerformed

    
    private void showFibo(int num) {
        
        for (int i = 0; i < num; i++) {
            outputArea.append("  "+fibo(i));
            
            if ((i + 1) % 5 == 0) outputArea.append("\n");
        }
    }
    
     
    private int fibo(int num) {
        if (num <= 1)
        {
            return 1;
        }else
        { 
            return fibo(num-1) + fibo(num-2);
        }
    }
    
    private void buttonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiveActionPerformed
        System.out.println("button five");
        outputArea.setText("");
        countDown(10);
    }//GEN-LAST:event_buttonFiveActionPerformed

    private void buttonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSixActionPerformed
        System.out.println("button six");
        outputArea.setText("");
        countDownAndUp(10);
    }//GEN-LAST:event_buttonSixActionPerformed

    
    private void countDownAndUp(int num) {
        if (num <= 1)
        {
            outputArea.append("  "+num);
        }else
        {
            outputArea.append("  "+num);
            countDownAndUp(num - 1);
            outputArea.append("  "+num);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFive;
    private javax.swing.JButton buttonFour;
    private javax.swing.JButton buttonOne;
    private javax.swing.JButton buttonSix;
    private javax.swing.JButton buttonThree;
    private javax.swing.JButton buttonTwo;
    private javax.swing.JTextField fieldFourInput;
    private javax.swing.JTextField fieldThreeInput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputArea;
    // End of variables declaration//GEN-END:variables
}
